spring:
  profiles:
    active: dev
  devtools:
    restart:
      log-condition-evaluation-delta: false
  sevlet:
    multipart:
      max-file-size: 10MB
  cache:
    ehcache:
      config: classpath:config/ehcache.xml



#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
mybatis-plus:
  type-aliases-package: com.ws.app.dao
#  mapper-locations: classpath:mapper/*.xml


cbuser: 1102,110207,110304,110204

ycsys-url: http://211.159.148.145:6021/WSCHweb/MeterEnterServlet