log:
  path: D://app//logs//app_dev_logs
  level: INFO

server:
  port: 8806
param:
  uuid: ${random.uuid}

# DataSource Config
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    data: classpath:db/data-h2.sql
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=WNT_万山
    username: sa
    password:
