spring:
  profiles:
    active: dev
  devtools:
    restart:
      log-condition-evaluation-delta: false
  sevlet:
    multipart:
      max-file-size: 10MB



#mybatis-plus:
#  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
#  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
mybatis-plus:
  type-aliases-package: com.ws.app.dao
#  mapper-locations: classpath:mapper/*.xml
